# Generated by Django 4.2.13 on 2024-06-11 14:07

from django.db import migrations, models
import snpt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=snpt.models.gen_slug, max_length=6, unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
