# Generated by Django 4.2.13 on 2024-06-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='slug',
            new_name='rand_slug',
        ),
    ]
