# Generated by Django 5.0.6 on 2024-06-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpt', '0002_rename_slug_codesnippet_rand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='rand_slug',
            new_name='slug',
        ),
    ]
